# Generated by Django 3.2.23 on 2023-11-28 14:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SceneItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronology', models.IntegerField(max_length=3)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('mono_dialogue', models.TextField(blank=True, max_length=300, null=True)),
                ('sketch_upload', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('excerpt', models.TextField(blank=True)),
                ('pin', models.IntegerField(choices=[(False, 'not pinned'), (True, 'Pinned')], default=False)),
            ],
            options={
                'ordering': ['chronology'],
            },
        ),
    ]
