# Generated by Django 3.2.23 on 2023-12-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='project_name',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
