# Generated by Django 3.2.23 on 2023-12-06 21:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectitem',
            name='project_artist_team',
        ),
        migrations.RemoveField(
            model_name='sceneitem',
            name='scene_test',
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='project_poster',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='sketchitem',
            name='sketch_directors_comment',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sketchitem',
            name='sketch_image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
