# Generated by Django 3.2.23 on 2023-11-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sceneitem',
            name='chronology',
            field=models.IntegerField(),
        ),
    ]
