# Generated by Django 3.2.23 on 2023-12-10 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeitem',
            name='episode_property_to_project',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='storyboard.projectitem'),
        ),
    ]
