# Generated by Django 3.2.23 on 2023-11-28 16:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0002_alter_sceneitem_chronology'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronology', models.IntegerField()),
                ('episode_name', models.CharField(default='None', max_length=50)),
                ('property_to_project', models.CharField(default='None', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['chronology'],
            },
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='My Project', max_length=50)),
                ('property_to_director', models.CharField(max_length=50)),
                ('artist_team', models.CharField(max_length=300)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['updated_date'],
            },
        ),
        migrations.CreateModel(
            name='SketchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sketch_upload', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('artist', models.CharField(default='None', max_length=50)),
                ('property_to_scene', models.CharField(default='None', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('pin', models.IntegerField(choices=[(0, 'not pinned'), (1, 'Pinned')], default=False)),
            ],
            options={
                'ordering': ['updated_date'],
            },
        ),
        migrations.RenameField(
            model_name='sceneitem',
            old_name='mono_dialogue',
            new_name='artist_assignment',
        ),
        migrations.RemoveField(
            model_name='sceneitem',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='sceneitem',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='sceneitem',
            name='sketch_upload',
        ),
        migrations.RemoveField(
            model_name='sceneitem',
            name='title',
        ),
        migrations.AddField(
            model_name='sceneitem',
            name='property_to_episode',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='sceneitem',
            name='scene_event_notes',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sceneitem',
            name='scene_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
