# Generated by Django 3.2.23 on 2023-12-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0002_auto_20231206_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketchitem',
            name='sketch_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sketchitem',
            name='sketch_slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
