# Generated by Django 3.2.23 on 2023-12-06 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0003_auto_20231206_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sketchitem',
            name='sketch_slug',
        ),
    ]
