# Generated by Django 3.2.23 on 2023-11-28 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storyboard', '0003_auto_20231128_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='test_owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='project_name',
            field=models.CharField(default='My project', max_length=50),
        ),
    ]
