# Generated by Django 3.2.23 on 2023-11-28 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storyboard', '0004_auto_20231128_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectitem',
            name='test_owner',
        ),
        migrations.AlterField(
            model_name='episodeitem',
            name='episode_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='episodeitem',
            name='property_to_project',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='project_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='property_to_director',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sceneitem',
            name='artist_assignment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sceneitem',
            name='property_to_episode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sceneitem',
            name='scene_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sketchitem',
            name='artist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sketchitem',
            name='property_to_scene',
            field=models.CharField(default='', max_length=50),
        ),
    ]
