# Generated by Django 3.2.23 on 2023-12-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0004_remove_sketchitem_sketch_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sketchitem',
            name='sketch_name',
        ),
    ]
