# Generated by Django 3.2.23 on 2023-12-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0004_episodeitem_episode_property_to_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodeitem',
            name='episode_property_to_director',
        ),
    ]
