# Generated by Django 3.2.23 on 2023-12-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0005_remove_episodeitem_episode_property_to_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketchitem',
            name='sketch_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
