# Generated by Django 3.2.23 on 2023-12-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0005_auto_20231128_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='SketchItemComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
