# Generated by Django 3.2.23 on 2023-12-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0006_auto_20231220_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodeitem',
            name='episode_property_to_director',
        ),
        migrations.RemoveField(
            model_name='sceneitem',
            name='scene_property_to_director',
        ),
        migrations.RemoveField(
            model_name='sketchitem',
            name='sketch_property_to_director',
        ),
    ]
