# Generated by Django 3.2.23 on 2023-12-17 21:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0006_alter_sketchitem_sketch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketchitem',
            name='sketch_image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
