# Generated by Django 3.2.23 on 2023-12-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0007_auto_20231201_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketchitemcomment',
            name='comment',
            field=models.TextField(default='', max_length=500),
        ),
    ]
