# Generated by Django 3.2.23 on 2023-12-22 12:38

import django.core.validators
from django.db import migrations, models
import storyboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0008_auto_20231220_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketchitem',
            name='sketch_image',
            field=models.ImageField(upload_to='images/', validators=[storyboard.models.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
