# Generated by Django 3.2.23 on 2023-12-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0008_alter_sketchitemcomment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sketchitemcomment',
            name='comment',
        ),
        migrations.AddField(
            model_name='sketchitemcomment',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
