# Generated by Django 3.2.23 on 2023-12-05 13:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0009_auto_20231201_1700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SketchItemComment',
        ),
        migrations.AlterModelOptions(
            name='episodeitem',
            options={'ordering': ['episode_chronology']},
        ),
        migrations.AlterModelOptions(
            name='projectitem',
            options={'ordering': ['project_updated_date']},
        ),
        migrations.AlterModelOptions(
            name='sceneitem',
            options={'ordering': ['scene_chronology']},
        ),
        migrations.AlterModelOptions(
            name='sketchitem',
            options={'ordering': ['sketch_updated_date']},
        ),
        migrations.RenameField(
            model_name='episodeitem',
            old_name='chronology',
            new_name='episode_chronology',
        ),
        migrations.RenameField(
            model_name='episodeitem',
            old_name='creation_date',
            new_name='episode_creation_date',
        ),
        migrations.RenameField(
            model_name='episodeitem',
            old_name='property_to_project',
            new_name='episode_property_to_project',
        ),
        migrations.RenameField(
            model_name='episodeitem',
            old_name='updated_date',
            new_name='episode_updated_date',
        ),
        migrations.RenameField(
            model_name='projectitem',
            old_name='artist_team',
            new_name='project_artist_team',
        ),
        migrations.RenameField(
            model_name='projectitem',
            old_name='creation_date',
            new_name='project_creation_date',
        ),
        migrations.RenameField(
            model_name='projectitem',
            old_name='property_to_director',
            new_name='project_property_to_director',
        ),
        migrations.RenameField(
            model_name='projectitem',
            old_name='updated_date',
            new_name='project_updated_date',
        ),
        migrations.RenameField(
            model_name='sceneitem',
            old_name='artist_assignment',
            new_name='scene_artist_assignment',
        ),
        migrations.RenameField(
            model_name='sceneitem',
            old_name='chronology',
            new_name='scene_chronology',
        ),
        migrations.RenameField(
            model_name='sceneitem',
            old_name='creation_date',
            new_name='scene_creation_date',
        ),
        migrations.RenameField(
            model_name='sceneitem',
            old_name='property_to_episode',
            new_name='scene_property_to_episode',
        ),
        migrations.RenameField(
            model_name='sceneitem',
            old_name='updated_date',
            new_name='scene_updated_date',
        ),
        migrations.RenameField(
            model_name='sketchitem',
            old_name='artist',
            new_name='sketch_artist',
        ),
        migrations.RenameField(
            model_name='sketchitem',
            old_name='creation_date',
            new_name='sketch_creation_date',
        ),
        migrations.RenameField(
            model_name='sketchitem',
            old_name='sketch_upload',
            new_name='sketch_item_upload',
        ),
        migrations.RenameField(
            model_name='sketchitem',
            old_name='pin',
            new_name='sketch_pin',
        ),
        migrations.RenameField(
            model_name='sketchitem',
            old_name='property_to_scene',
            new_name='sketch_property_to_scene',
        ),
        migrations.RenameField(
            model_name='sketchitem',
            old_name='updated_date',
            new_name='sketch_updated_date',
        ),
        migrations.AddField(
            model_name='episodeitem',
            name='episode_slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='project_poster',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='project_slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='sceneitem',
            name='scene_slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='sketchitem',
            name='sketch_directors_comment',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='project_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
