# Generated by Django 3.2.23 on 2023-12-05 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0010_auto_20231205_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodeitem',
            name='episode_property_to_project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='storyboard.projectitem'),
        ),
        migrations.AlterField(
            model_name='sceneitem',
            name='scene_property_to_episode',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='storyboard.episodeitem'),
        ),
        migrations.AlterField(
            model_name='sketchitem',
            name='sketch_property_to_scene',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='storyboard.sceneitem'),
        ),
    ]
