# Generated by Django 3.2.23 on 2023-12-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0011_auto_20231205_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sketchitem',
            name='sketch_artist',
        ),
        migrations.RemoveField(
            model_name='sketchitem',
            name='sketch_item_upload',
        ),
        migrations.RemoveField(
            model_name='sketchitem',
            name='sketch_pin',
        ),
        migrations.RemoveField(
            model_name='sketchitem',
            name='sketch_property_to_scene',
        ),
    ]
